version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/onebitbot'
    #definindo variável de ambiente
    environment:
      - LANG=C.UTF-8

volumes:
  postgres:
